#! /bin/sh

sxhkd &

compton --config $HOME/.config/compton/compton.conf &

xrandr --output HDMI-1 --mode 800x600
xrandr --output eDP-1 --mode 800x600
xrandr --output HDMI-1  --mode 1280x720 
xrandr --output HDMI-1 --pos 0x0 --rotate normal 
xrandr --output eDP-1 --mode 1920x1080 
xrandr --output eDP-1 --pos 1280x0 --rotate normal
xrandr --output HDMI-1 --primary

bspc monitor HDMI-1 -d I II III IV V 
bspc monitor eDP-1 -d VI VII VIII IX X

xsetroot -cursor_name left_ptr

feh --bg-fill ~/Pictures/wallhaven-wy1lyr.jpg

$HOME/.config/polybar/launch.sh

setxkbmap -option caps:swapescape

unclutter &

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# Border colors
bspc config normal_border_color "#B58900"
bspc config focused_border_color "#e1cf99"
bspc config urgent_border_color "#E1AB99"
bspc config presel_border_color "#26E2FF"

# Padding
bspc config -m HDMI-1 top_padding  40
bspc config -m HDMI-1 bottom_padding  12

bspc rule -a Firefox state=tiled follow=on
bspc rule -a Zathura state=tiled follow=on
bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
